apiVersion: v1
kind: Service
metadata:
  name: behemoth-nodejs-catalog-service
  namespace: behemoth
spec:
  selector:
    app: behemoth-nodejs-catalog
  ports:
    - port: 80
      targetPort: 3020
  type: ClusterIP
