apiVersion: v1
kind: Service
metadata:
  name: behemoth-nodejs-catalog-service
spec:
  selector:
    app: behemoth-nodejs-catalog-service
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
