apiVersion: v1
kind: Service
metadata:
  name: behemoth-nodejs-review-service
  namespace: behemoth
spec:
  selector:
    app: behemoth-nodejs-review
  ports:
    - port: 80
      targetPort: 3030
  type: ClusterIP
