apiVersion: v1
kind: Service
metadata:
  name: behemoth-nodejs-auth
spec:
  selector:
    app.kubernetes.io/name: behemoth-nodejs-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3010
  type: ClusterIP
