resources:
  - ../../base
  - loki.yaml
  - promtail.yaml
  - grafana.yaml
  - loki-service.yaml
  - promtail-config.yaml
  - grafana-datasource.yaml
  - promtail-sa.yaml
  - promtail-clusterrole.yaml
  - promtail-clusterrolebinding.yaml
