apiVersion: v1
kind: Service
metadata:
  name: behemoth-nodejs-review
spec:
  selector:
    app.kubernetes.io/name: behemoth-nodejs-review
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: ClusterIP
