apiVersion: v1
kind: Service
metadata:
  name: behemoth-nodejs-review
spec:
  selector:
    app.kubernetes.io/name: behemoth-nodejs-review
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 3030
    - name: http-metrics
      protocol: TCP
      port: 8081
      targetPort: 3030
  type: ClusterIP
