apiVersion: apps/v1
kind: Deployment
metadata:
  name: behemoth-react-fe
  namespace: behemoth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: behemoth-react-fe
  template:
    metadata:
      labels:
        app: behemoth-react-fe
    spec:
      containers:
        - name: behemoth-react-fe
          image: registry.local:5000/behemoth-react-fe:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
