apiVersion: v1
kind: Service
metadata:
  name: behemoth-react-fe-service
  namespace: behemoth
spec:
  selector:
    app: behemoth-react-fe
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
