apiVersion: apps/v1
kind: Deployment
metadata:
  name: behemoth-preact-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: behemoth-preact-fe
  template:
    metadata:
      labels:
        app: behemoth-preact-fe
    spec:
      containers:
      - name: preact-fe
        image: alfathmuqoddas/behemoth-preact-fe:latest
        ports:
        - containerPort: 80
        env:
        - name: API_AUTH_URL
          value: "http://behemoth-nodejs-auth-service.app.svc.cluster.local"
        - name: API_CATALOG_URL
          value: "http://behemoth-nodejs-catalog-service.app.svc.cluster.local"
        - name: API_REVIEW_URL
          value: "http://behemoth-nodejs-review-service.app.svc.cluster.local"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
