apiVersion: v1
kind: Service
metadata:
  name: behemoth-nodejs-catalog
spec:
  selector:
    app.kubernetes.io/name: behemoth-nodejs-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3020
  type: ClusterIP
